### ISSUE TITLE
Copyright Attribution

### ISSUE THREAD

**Issue by Fyorl** [Mejari/kw_warfare#1]
Hi,

Very happy to have someone building on top of my GPL code, that's half the point, after all. I did notice this line in the License section, however:

> All source code is copyright 2021 Dylan Gulick

I don't believe you can claim copyright to *all* the source code, given that some of it has been copied without modification from my own repo, and I still hold the copyright to those sections. Perhaps something like:

> All additions and modifications to the source code are copyright...

Though I recognise that the *vast majority* of the repo is new code so perhaps 'additions and modification' is underselling it.

**Comment by Mejari** [comment]
Will absolutely do that, sorry about that. This is my first time doing something like this so I'm bound to make some mistakes.

**Comment by Fyorl** [comment]
No problem at all, thanks for the fast response.
