### ISSUE TITLE
Can't install the module in Foundry VTT 0.8.7

### ISSUE THREAD

**Issue by Selkmanam** [Mejari/kw_warfare#2]
![ssd](https://user-images.githubusercontent.com/88949189/129460423-2b238554-e53c-4406-8960-371b3f363ae6.PNG)

**Comment by Mejari** [comment]
The path to the module.json should be the raw text version, not the github page for it. Try using `https://raw.githubusercontent.com/Mejari/kw_warfare/main/module.json`

**Comment by Selkmanam** [comment]
Works with the raw link, noob mistake.
