### ISSUE TITLE
Can't edit the Type on Unit

### ISSUE THREAD

**Issue by dsakura** [Mejari/kw_warfare#6]
Hello! How can I add the types on the unit? All itens that I drag to the sheet becomes feature. Thank you

**Comment by Mejari** [comment]
Have you set the feature's "Requirement" field as described in the How-To section of the readme?

**Comment by dsakura** [comment]
My bad, working.. Distraction on my part, I tried to delete the message here later, but I couldn't. sorry and thank you very much. Helping me a lot with the warfare
